import img from "../img/banner.png";

export const sportsbooks = [
  {
    id: 0,
    name: "Abet",
    img: img,
    imageAlt: "Abet",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 0,
    stars: 5,
    countries: ["Costa Rica", "Panamá", "Argentina"],
    top: 1,
    casino: "✓",
    betBuilder: "✓",
    cs: "X",
    enVivo: "X",
    cashOut: "✓",
    referidos: "X",
  },
  {
    id: 1,
    name: "Bet365",
    img: img,
    imageAlt: "Bet365",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 0,
    stars: 1,
    countries: ["Costa Rica", "Argentina"],
    top: 1,
    casino: "X",
    betBuilder: "✓",
    cs: "X",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
  },
  {
    id: 2,
    name: "Poker Stars",
    img: img,
    imageAlt: "Poker Stars",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 1,
    stars: 4,
    countries: ["Costa Rica"],
    casino: "✓",
    betBuilder: "✓",
    cs: "X",
    enVivo: "✓",
    cashOut: "✓",
    referidos: "X",
  },
  {
    id: 3,
    name: "LeoVegas",
    img: img,
    imageAlt: "LeoVegas",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 0,
    stars: 2,
    countries: ["Panamá"],
    top: 1,
    casino: "X",
    betBuilder: "✓",
    cs: "✓",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
  },
  {
    id: 4,
    name: "Betsson",
    img: img,
    imageAlt: "Betsson",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 1,
    stars: 4,
    countries: ["Costa Rica", "Colombia"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "✓",
    cashOut: "✓",
    referidos: "✓",
  },
  {
    id: 5,
    name: "Sportsbet",
    img: img,
    imageAlt: "Sportsbet",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 1,
    stars: 5,
    countries: ["Argentina"],
    top: 1,
    casino: "✓",
    betBuilder: "X",
    cs: "✓",
    enVivo: "X",
    cashOut: "✓",
    referidos: "X",
  },
  {
    id: 6,
    name: "William Hill",
    img: img,
    imageAlt: "William Hill",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 1,
    stars: 1,
    countries: ["Costa Rica", "Panamá"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "✓",
    cashOut: "X",
    referidos: "✓",
  },
  {
    id: 7,
    name: "Betsafe",
    img: img,
    imageAlt: "Betsafe",
    description:
      "This is the content of the card. Lorem ipsum dolor sit amet consectetur adipiscing sdadsad asdasswq.",
    popular: 0,
    stars: 3,
    countries: ["Costa Rica", "Panamá", "Argentina", "Colombia"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
  },
];
