import android from "../img/apps/android.png";
import ios from "../img/apps/ios.png";
import appmovil from "../img/apps/app_movil.png";
import img from "../img/banner.png";

export const sportsbooks = [
  {
    id: 0,
    name: "Abet",
    img: img,
    imageAlt: "Abet",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 0,
    stars: 5,
    countries: ["Costa Rica", "Panamá", "Argentina"],
    top: 1,
    casino: "✓",
    betBuilder: "✓",
    cs: "X",
    enVivo: "X",
    cashOut: "✓",
    referidos: "X",
    metoPagos: ["Nequi", "Transferencia Bancaria"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android, ios, appmovil],
  },
  {
    id: 1,
    name: "Bet365",
    img: img,
    imageAlt: "Bet365",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 0,
    stars: 1,
    countries: ["Costa Rica", "Argentina"],
    top: 1,
    casino: "X",
    betBuilder: "✓",
    cs: "X",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
    metoPagos: ["Nequi", "Transferencia Bancaria"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android],
  },
  {
    id: 2,
    name: "Poker Stars",
    img: img,
    imageAlt: "Poker Stars",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 1,
    stars: 4,
    countries: ["Costa Rica"],
    casino: "✓",
    betBuilder: "✓",
    cs: "X",
    enVivo: "✓",
    cashOut: "✓",
    referidos: "X",
    metoPagos: ["Nequi"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android, ios, appmovil],
  },
  {
    id: 3,
    name: "LeoVegas",
    img: img,
    imageAlt: "LeoVegas",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 0,
    stars: 2,
    countries: ["Panamá"],
    top: 1,
    casino: "X",
    betBuilder: "✓",
    cs: "✓",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
    metoPagos: [
      "Criptomonedas",
      "Transferencia Bancaria",
      "Nequi",
      "Visa/Master Card",
      "Oxxo",
    ],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android, ios, appmovil],
  },
  {
    id: 4,
    name: "Betsson",
    img: img,
    imageAlt: "Betsson",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 1,
    stars: 4,
    countries: ["Costa Rica", "Colombia"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "✓",
    cashOut: "✓",
    referidos: "✓",
    metoPagos: ["Criptomonedas", "Visa/Master Card"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android, ios],
  },
  {
    id: 5,
    name: "Sportsbet",
    img: img,
    imageAlt: "Sportsbet",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 1,
    stars: 5,
    countries: ["Argentina"],
    top: 1,
    casino: "✓",
    betBuilder: "X",
    cs: "✓",
    enVivo: "X",
    cashOut: "✓",
    referidos: "X",
    metoPagos: ["Nequi", "Visa/Master Card"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [ios, appmovil],
  },
  {
    id: 6,
    name: "William Hill",
    img: img,
    imageAlt: "William Hill",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 1,
    stars: 1,
    countries: ["Costa Rica", "Panamá"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "✓",
    cashOut: "X",
    referidos: "✓",
    metoPagos: ["Criptomonedas", "Nequi"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [ios, appmovil],
  },
  {
    id: 7,
    name: "Betsafe",
    img: img,
    imageAlt: "Betsafe",
    description: "Bono de bienvenida del 100% con tu primer deposito.",
    popular: 0,
    stars: 3,
    countries: ["Costa Rica", "Panamá", "Argentina", "Colombia"],
    casino: "X",
    betBuilder: "X",
    cs: "✓",
    enVivo: "X",
    cashOut: "X",
    referidos: "✓",
    metoPagos: ["Criptomonedas", "Visa/Master Card"],
    ventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    desventajas: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec feugiat ligula. Sed dignissim neque eu mollis eleifend.",
    ],
    app: [android, ios, appmovil],
  },
];
